#!/usr/bin/env bash
set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

DOTFILES_DIR="$(cd "$(dirname "$0")" && pwd)"
BACKUP_DIR="$HOME/.dotfiles_backup/$(date +%Y%m%d_%H%M%S)"
OS="$(uname -s)"
CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
PARAMS_FILE="$HOME/.params_for_dotfiles"
LEGACY_PARAMS_FILE="$CONFIG_HOME/dotfiles/params.env"
LOCAL_GIT_DIR="$CONFIG_HOME/git"
LOCAL_GIT_CONFIG="$LOCAL_GIT_DIR/user.gitconfig"
LEGACY_GIT_NAME="Siddarth G"
LEGACY_GIT_EMAIL="sidgoyal23@gmail.com"

mkdir -p "$HOME/.local/bin"
export PATH="$HOME/.local/bin:$PATH"

info()  { echo -e "${BLUE}[INFO]${NC} $1"; }
ok()    { echo -e "${GREEN}[OK]${NC} $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
err()   { echo -e "${RED}[ERROR]${NC} $1"; }

confirm() {
    local prompt="$1"
    local reply

    while true; do
        printf "%s [y/N] " "$prompt"
        read -r reply || {
            echo ""
            return 1
        }
        case "$reply" in
            [Yy]|[Yy][Ee][Ss]) return 0 ;;
            ""|[Nn]|[Nn][Oo]) return 1 ;;
            *) warn "Please answer yes or no." ;;
        esac
    done
}

quote_env_value() {
    local value="$1"
    value="${value//\\/\\\\}"
    value="${value//\"/\\\"}"
    value="${value//\$/\\\$}"
    value="${value//\`/\\\`}"
    printf '"%s"' "$value"
}

load_dotfiles_params() {
    if [[ -f "$PARAMS_FILE" ]]; then
        # shellcheck disable=SC1090
        source "$PARAMS_FILE"
    elif [[ -f "$LEGACY_PARAMS_FILE" ]]; then
        warn "Using legacy params file at $LEGACY_PARAMS_FILE; run ./install.sh personalize to write $PARAMS_FILE"
        # shellcheck disable=SC1090
        source "$LEGACY_PARAMS_FILE"
    fi

    DOTFILES_GIT_NAME="${DOTFILES_GIT_NAME:-}"
    DOTFILES_GIT_EMAIL="${DOTFILES_GIT_EMAIL:-}"
    DOTFILES_EDITOR="${DOTFILES_EDITOR:-nvim}"
    DOTFILES_NERD_FONT="${DOTFILES_NERD_FONT:-Hack}"
    DOTFILES_LOCALE="${DOTFILES_LOCALE:-}"
    DOTFILES_GIT_CREDENTIAL_HELPER="${DOTFILES_GIT_CREDENTIAL_HELPER:-}"
    DOTFILES_GIT_DIFFTOOL="${DOTFILES_GIT_DIFFTOOL:-}"
}

global_git_value() {
    local key="$1"
    local value
    value="$(git config --global --get "$key" 2>/dev/null || true)"

    case "$key:$value" in
        "user.name:$LEGACY_GIT_NAME"|"user.email:$LEGACY_GIT_EMAIL")
            return 1
            ;;
    esac

    [[ -n "$value" ]] || return 1
    printf '%s' "$value"
}

seed_git_identity_from_global() {
    local value

    if [[ -z "$DOTFILES_GIT_NAME" ]]; then
        value="$(global_git_value user.name || true)"
        if [[ -n "$value" ]]; then
            DOTFILES_GIT_NAME="$value"
            info "Using existing Git author name: $DOTFILES_GIT_NAME"
        fi
    fi

    if [[ -z "$DOTFILES_GIT_EMAIL" ]]; then
        value="$(global_git_value user.email || true)"
        if [[ -n "$value" ]]; then
            DOTFILES_GIT_EMAIL="$value"
            info "Using existing Git author email: $DOTFILES_GIT_EMAIL"
        fi
    fi
}

prompt_for_git_identity() {
    while [[ -z "$DOTFILES_GIT_NAME" ]]; do
        printf "Git author name: "
        if ! read -r DOTFILES_GIT_NAME; then
            echo ""
            err "Git author name is required"
            exit 1
        fi
        [[ -n "$DOTFILES_GIT_NAME" ]] || warn "Git author name cannot be empty."
    done

    while [[ -z "$DOTFILES_GIT_EMAIL" ]]; do
        printf "Git author email: "
        if ! read -r DOTFILES_GIT_EMAIL; then
            echo ""
            err "Git author email is required"
            exit 1
        fi
        [[ -n "$DOTFILES_GIT_EMAIL" ]] || warn "Git author email cannot be empty."
    done
}

write_params_file() {
    cat > "$PARAMS_FILE" << EOF
# Dotfiles local parameters
# This file belongs to this machine/user only.
# Edit the supported values below, then run ./install.sh personalize.
# This file is regenerated by the installer and should not be committed to the repo.

# Git identity used for commits.
# Example:
# DOTFILES_GIT_NAME="Jane Doe"
# DOTFILES_GIT_EMAIL="jane@example.com"
DOTFILES_GIT_NAME=$(quote_env_value "$DOTFILES_GIT_NAME")
DOTFILES_GIT_EMAIL=$(quote_env_value "$DOTFILES_GIT_EMAIL")

# Default editor used by Git and shell tools.
# Example: "nvim", "vim", "code --wait"
DOTFILES_EDITOR=$(quote_env_value "$DOTFILES_EDITOR")

# Nerd Font to install.
# Example: "Hack", "JetBrainsMono", "FiraCode"
DOTFILES_NERD_FONT=$(quote_env_value "$DOTFILES_NERD_FONT")

# Optional locale override.
# Leave empty to use your system's existing locale.
# Example: "en_US.UTF-8"
DOTFILES_LOCALE=$(quote_env_value "$DOTFILES_LOCALE")

# Optional Git credential helper.
# Leave empty to auto-detect. Use "gh" if you use GitHub CLI.
# Example: "gh"
DOTFILES_GIT_CREDENTIAL_HELPER=$(quote_env_value "$DOTFILES_GIT_CREDENTIAL_HELPER")

# Optional Git difftool.
# Leave empty to skip difftool setup.
# Example: "vscode"
DOTFILES_GIT_DIFFTOOL=$(quote_env_value "$DOTFILES_GIT_DIFFTOOL")
EOF
    ok "Wrote $PARAMS_FILE"
}

write_local_git_config() {
    local credential_helper="$DOTFILES_GIT_CREDENTIAL_HELPER"
    local difftool="$DOTFILES_GIT_DIFFTOOL"

    if [[ -z "$credential_helper" ]] && command -v gh &>/dev/null; then
        credential_helper="gh"
    fi

    mkdir -p "$LOCAL_GIT_DIR"
    cat > "$LOCAL_GIT_CONFIG" << EOF
# Generated by dotfiles-setup.
# Edit $PARAMS_FILE, then run ./install.sh personalize to regenerate.

[user]
	name = $DOTFILES_GIT_NAME
	email = $DOTFILES_GIT_EMAIL

[core]
	editor = $DOTFILES_EDITOR
EOF

    if [[ -n "$credential_helper" ]]; then
        if [[ "$credential_helper" == "gh" ]]; then
            if ! command -v gh &>/dev/null; then
                warn "DOTFILES_GIT_CREDENTIAL_HELPER=gh, but gh is not currently on PATH"
            fi
            cat >> "$LOCAL_GIT_CONFIG" << 'EOF'

[credential "https://github.com"]
	helper =
	helper = !gh auth git-credential

[credential "https://gist.github.com"]
	helper =
	helper = !gh auth git-credential
EOF
        else
            cat >> "$LOCAL_GIT_CONFIG" << EOF

[credential]
	helper = $credential_helper
EOF
        fi
    fi

    if [[ -n "$difftool" ]]; then
        case "$difftool" in
            vscode|code)
                if ! command -v code &>/dev/null; then
                    warn "DOTFILES_GIT_DIFFTOOL=$difftool, but code is not currently on PATH"
                fi
                cat >> "$LOCAL_GIT_CONFIG" << 'EOF'

[diff]
	tool = vscode

[difftool]
	prompt = false

[difftool "vscode"]
	cmd = code -dw "$LOCAL" "$REMOTE"
EOF
                ;;
            *)
                cat >> "$LOCAL_GIT_CONFIG" << EOF

[diff]
	tool = $difftool

[difftool]
	prompt = false
EOF
                ;;
        esac
    fi

    ok "Wrote $LOCAL_GIT_CONFIG"
}

install_personal_config() {
    info "Setting up local dotfiles parameters..."
    load_dotfiles_params
    seed_git_identity_from_global
    prompt_for_git_identity
    write_params_file
    write_local_git_config
}

# ─── Pre-flight ───────────────────────────────────────────────────────────────

preflight() {
    for cmd in git curl; do
        if ! command -v "$cmd" &>/dev/null; then
            err "$cmd is required but not found. Install it first:"
            if [[ "$OS" == "Linux" ]]; then
                err "  sudo apt install $cmd   (Debian/Ubuntu)"
                err "  sudo dnf install $cmd   (Fedora/RHEL)"
            else
                err "  xcode-select --install  (macOS)"
            fi
            exit 1
        fi
    done
    ok "Pre-flight checks passed (git, curl found)"
}

preflight_git() {
    if ! command -v git &>/dev/null; then
        err "git is required but not found. Install it first:"
        if [[ "$OS" == "Linux" ]]; then
            err "  sudo apt install git   (Debian/Ubuntu)"
            err "  sudo dnf install git   (Fedora/RHEL)"
        else
            err "  xcode-select --install  (macOS)"
        fi
        exit 1
    fi
    ok "Pre-flight checks passed (git found)"
}

# ─── Backup existing configs ─────────────────────────────────────────────────

backup_if_exists() {
    local target="$1"
    if [[ -e "$target" || -L "$target" ]]; then
        mkdir -p "$BACKUP_DIR"
        mv "$target" "$BACKUP_DIR/"
        warn "Backed up $target → $BACKUP_DIR/"
    fi
}

backup() {
    info "Backing up existing configs..."
    backup_if_exists "$HOME/.zshenv"
    backup_if_exists "$HOME/.zshrc"
    backup_if_exists "$HOME/.gitconfig"
    backup_if_exists "$HOME/.tmux.conf"
    backup_if_exists "$HOME/.config/nvim"
    backup_if_exists "$HOME/.config/starship.toml"
    backup_if_exists "$HOME/.config/bat"
    backup_if_exists "$HOME/.config/ripgrep"
    backup_if_exists "$HOME/.config/fd"
    backup_if_exists "$HOME/.config/zsh"
    ok "Backup complete"
}

# ─── Install packages ────────────────────────────────────────────────────────

install_packages() {
    if [[ "$OS" == "Darwin" ]]; then
        info "Detected macOS"

        # Install Homebrew if missing
        if ! command -v brew &>/dev/null; then
            info "Installing Homebrew..."
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        fi
        # Apple Silicon: /opt/homebrew; Intel Mac: /usr/local (see https://docs.brew.sh/Installation)
        if [[ -x /opt/homebrew/bin/brew ]]; then
            eval "$(/opt/homebrew/bin/brew shellenv)"
        elif [[ -x /usr/local/bin/brew ]]; then
            eval "$(/usr/local/bin/brew shellenv)"
        fi

        info "Installing packages via Homebrew..."
        brew bundle --file="$DOTFILES_DIR/Brewfile"

    elif [[ "$OS" == "Linux" ]]; then
        info "Detected Linux"

        if command -v apt &>/dev/null; then
            info "Installing packages via apt..."
            sudo apt update
            sudo apt install -y \
                zsh stow ripgrep bat tmux unzip \
                nodejs npm curl git xclip wl-clipboard

            # eza: only when packaged in your release (e.g. Ubuntu 24.04+ universe); skip otherwise
            if apt-cache show eza &>/dev/null; then
                sudo apt install -y eza
            else
                info "eza not in default apt repos for this release; ls aliases fall back to standard ls"
            fi

            # fd-find has a different package name on Debian/Ubuntu
            sudo apt install -y fd-find || true

            # bat binary is 'batcat' on Debian/Ubuntu — symlink to ~/.local/bin
            if command -v batcat &>/dev/null && ! command -v bat &>/dev/null; then
                ln -sf "$(which batcat)" "$HOME/.local/bin/bat"
            fi

            # fd binary is 'fdfind' on Debian/Ubuntu — symlink to ~/.local/bin
            if command -v fdfind &>/dev/null && ! command -v fd &>/dev/null; then
                ln -sf "$(which fdfind)" "$HOME/.local/bin/fd"
            fi

        elif command -v dnf &>/dev/null; then
            info "Installing packages via dnf..."
            sudo dnf install -y \
                zsh stow ripgrep fd-find bat eza tmux unzip \
                nodejs npm curl git xclip wl-clipboard

        else
            err "Unsupported package manager. Install packages manually."
            exit 1
        fi

        # ── Rootless binary installs to ~/.local/bin ──────────────────────
        local arch
        arch="$(uname -m)"

        # Neovim (apt/dnf ship outdated versions missing vim.keymap etc.)
        if ! command -v nvim &>/dev/null || [[ "$(nvim --version | head -1 | sed 's/[^0-9]*\([0-9]*\)\.\([0-9]*\).*/\1\2/')" -lt "09" ]]; then
            info "Installing Neovim (latest stable) to ~/.local/bin..."
            local nvim_arch
            case "$arch" in
                x86_64)        nvim_arch="x86_64" ;;
                aarch64|arm64) nvim_arch="arm64" ;;
                *)             warn "nvim: unsupported architecture $arch" ;;
            esac
            if [[ -n "${nvim_arch:-}" ]]; then
                local nvim_tmp
                nvim_tmp="$(mktemp -d)"
                curl -fsSL "https://github.com/neovim/neovim/releases/latest/download/nvim-linux-${nvim_arch}.tar.gz" \
                    | tar xz -C "$nvim_tmp"
                cp -r "$nvim_tmp"/nvim-linux-${nvim_arch}/* "$HOME/.local/"
                rm -rf "$nvim_tmp"
                ok "Neovim installed"
            fi
        fi

        # fzf (always install latest to ~/.local/bin to override outdated system versions)
        {
            info "Installing fzf to ~/.local/bin..."
            local fzf_arch
            case "$arch" in
                x86_64)        fzf_arch="amd64" ;;
                aarch64|arm64) fzf_arch="arm64" ;;
                *)             warn "fzf: unsupported architecture $arch" ;;
            esac
            if [[ -n "${fzf_arch:-}" ]]; then
                local fzf_ver
                fzf_ver="$(curl -sS https://api.github.com/repos/junegunn/fzf/releases/latest \
                    | grep '"tag_name"' | head -1 | sed 's/.*"v\(.*\)".*/\1/')"
                curl -fsSL "https://github.com/junegunn/fzf/releases/download/v${fzf_ver}/fzf-${fzf_ver}-linux_${fzf_arch}.tar.gz" \
                    | tar xz -C "$HOME/.local/bin"
                ok "fzf ${fzf_ver} installed"
            fi
        }

        # zoxide
        if ! command -v zoxide &>/dev/null; then
            info "Installing zoxide to ~/.local/bin..."
            curl -sSfL https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh \
                | sh -s -- --bin-dir "$HOME/.local/bin" --man-dir "$HOME/.local/share/man"
            ok "zoxide installed"
        fi

        # git-delta
        if ! command -v delta &>/dev/null; then
            info "Installing git-delta to ~/.local/bin..."
            local delta_arch
            case "$arch" in
                x86_64)        delta_arch="x86_64" ;;
                aarch64|arm64) delta_arch="aarch64" ;;
                *)             warn "git-delta: unsupported architecture $arch" ;;
            esac
            if [[ -n "${delta_arch:-}" ]]; then
                local delta_ver delta_tmp
                delta_ver="$(curl -sS https://api.github.com/repos/dandavison/delta/releases/latest \
                    | grep '"tag_name"' | head -1 | sed 's/.*"\(.*\)".*/\1/')"
                delta_tmp="$(mktemp -d)"
                curl -fsSL "https://github.com/dandavison/delta/releases/download/${delta_ver}/delta-${delta_ver}-${delta_arch}-unknown-linux-gnu.tar.gz" \
                    | tar xz -C "$delta_tmp"
                cp "$delta_tmp/delta-${delta_ver}-${delta_arch}-unknown-linux-gnu/delta" "$HOME/.local/bin/"
                rm -rf "$delta_tmp"
                ok "git-delta ${delta_ver} installed"
            fi
        fi

        # Starship
        if ! command -v starship &>/dev/null; then
            info "Installing Starship to ~/.local/bin..."
            curl -sS https://starship.rs/install.sh | sh -s -- --bin-dir "$HOME/.local/bin" --yes
        fi
    fi
    ok "Packages installed"
}

# ─── Install oh-my-zsh ───────────────────────────────────────────────────────

install_omz() {
    if [[ ! -d "$HOME/.oh-my-zsh" ]]; then
        info "Installing oh-my-zsh..."
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" \
            --unattended --keep-zshrc
        # oh-my-zsh creates ~/.zshrc even with --keep-zshrc; remove it since we use ZDOTDIR
        rm -f "$HOME/.zshrc"
        ok "oh-my-zsh installed"
    else
        ok "oh-my-zsh already installed"
    fi
}

# ─── Clone oh-my-zsh custom plugins ──────────────────────────────────────────

install_omz_plugins() {
    local ZSH_CUSTOM="${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}"

    clone_plugin() {
        local repo="$1"
        local name="$(basename "$repo")"
        local dest="$ZSH_CUSTOM/plugins/$name"

        if [[ ! -d "$dest" ]]; then
            info "Cloning $name..."
            git clone "https://github.com/$repo.git" "$dest"
        else
            ok "$name already installed"
        fi
    }

    clone_plugin "zsh-users/zsh-autosuggestions"
    clone_plugin "zsh-users/zsh-syntax-highlighting"
    clone_plugin "zsh-users/zsh-history-substring-search"
    clone_plugin "zsh-users/zsh-completions"
    clone_plugin "Aloxaf/fzf-tab"
    ok "oh-my-zsh plugins installed"
}

# ─── Clone TPM (Tmux Plugin Manager) ─────────────────────────────────────────

install_tpm() {
    if [[ ! -d "$HOME/.tmux/plugins/tpm" ]]; then
        info "Installing TPM..."
        git clone https://github.com/tmux-plugins/tpm "$HOME/.tmux/plugins/tpm"
        ok "TPM installed"
    else
        ok "TPM already installed"
    fi
}

# ─── Install Nerd Font ───────────────────────────────────────────────────────

install_nerd_font() {
    load_dotfiles_params

    local font_name="$DOTFILES_NERD_FONT"
    local font_zip="${font_name}.zip"
    local font_url="https://github.com/ryanoasis/nerd-fonts/releases/latest/download/${font_zip}"

    if [[ "$OS" == "Darwin" ]]; then
        local font_dir="$HOME/Library/Fonts"
    else
        local font_dir="$HOME/.local/share/fonts"
    fi

    # Check if already installed
    if ls "$font_dir"/"${font_name}"*NerdFont* &>/dev/null 2>&1; then
        ok "$font_name Nerd Font already installed"
        return
    fi

    info "Installing $font_name Nerd Font..."
    mkdir -p "$font_dir"

    local tmp_dir
    tmp_dir="$(mktemp -d)"
    curl -fsSL "$font_url" -o "$tmp_dir/$font_zip"
    unzip -qo "$tmp_dir/$font_zip" -d "$tmp_dir/font"
    cp "$tmp_dir"/font/*.ttf "$font_dir/"
    rm -rf "$tmp_dir"

    # Rebuild font cache on Linux
    if [[ "$OS" == "Linux" ]] && command -v fc-cache &>/dev/null; then
        fc-cache -f "$font_dir"
    fi

    ok "$font_name Nerd Font installed to $font_dir"
}

# ─── Stow all packages ───────────────────────────────────────────────────────

create_zshrc_compat_symlink() {
    local source="$HOME/.config/zsh/.zshrc"
    local target="$HOME/.zshrc"

    if [[ ! -e "$source" ]]; then
        warn "Skipping ~/.zshrc compatibility symlink; $source does not exist"
        return
    fi

    if [[ -L "$target" && "$(readlink "$target")" == "$source" ]]; then
        ok "~/.zshrc already points to $source"
        return
    fi

    if [[ -e "$target" || -L "$target" ]]; then
        warn "$target already exists"
        if confirm "Back it up to $BACKUP_DIR and use the repo-managed .zshrc instead?"; then
            backup_if_exists "$target"
        else
            warn "Leaving $target unchanged"
            return
        fi
    fi

    if [[ -e "$target" || -L "$target" ]]; then
        warn "Could not replace $target; leaving it unchanged"
        return
    fi

    ln -s "$source" "$target"
    ok "Linked $target -> $source"
}

install_stow() {
    info "Creating symlinks with stow..."
    cd "$DOTFILES_DIR"

    # Ensure ~/.config exists
    mkdir -p "$HOME/.config"

    stow_packages=(zsh git starship nvim tmux bat ripgrep fd)
    for pkg in "${stow_packages[@]}"; do
        stow -v -d "$DOTFILES_DIR" -t "$HOME" "$pkg"
        ok "Stowed $pkg"
    done

    create_zshrc_compat_symlink
}

# ─── Create local config template ────────────────────────────────────────────

install_local_conf() {
    local LOCAL_CONF="$HOME/.config/zsh/conf.d/99-local.zsh"
    if [[ ! -f "$LOCAL_CONF" ]]; then
        cat > "$LOCAL_CONF" << 'EOF'
# Machine-specific configuration (gitignored)
# Add your local PATH additions, work-specific aliases, etc. here

EOF
        ok "Created $LOCAL_CONF (edit for machine-specific config)"
    else
        ok "99-local.zsh already exists"
    fi
}

# ─── Set default shell ───────────────────────────────────────────────────────

install_default_shell() {
    local current_shell="${SHELL:-}"
    local zsh_path
    local current_user

    if [[ "$(basename "$current_shell")" == "zsh" ]]; then
        ok "zsh is already the default shell ($current_shell)"
        return
    fi

    zsh_path="$(command -v zsh || true)"
    if [[ -z "$zsh_path" ]]; then
        err "zsh is required but not found"
        exit 1
    fi

    if [[ -f /etc/shells ]] && ! grep -Fxq "$zsh_path" /etc/shells; then
        if [[ -x /bin/zsh ]] && grep -Fxq /bin/zsh /etc/shells; then
            warn "$zsh_path is not listed in /etc/shells; using /bin/zsh instead"
            zsh_path="/bin/zsh"
        else
            info "Adding $zsh_path to /etc/shells..."
            if ! echo "$zsh_path" | sudo tee -a /etc/shells > /dev/null; then
                warn "Could not add $zsh_path to /etc/shells; skipping default shell change"
                return
            fi
        fi
    fi

    info "Setting zsh as default shell..."
    current_user="$(whoami)"

    # sudo chsh avoids chsh's own interactive password prompt.
    if sudo chsh -s "$zsh_path" "$current_user"; then
        ok "Default shell set to zsh"
    else
        warn "Could not set default shell automatically."
        warn "Run manually: sudo chsh -s $zsh_path $current_user"
    fi
}

# ─── Summary ─────────────────────────────────────────────────────────────────

summary() {
    echo ""
    echo -e "${GREEN}════════════════════════════════════════════════${NC}"
    echo -e "${GREEN}  Dotfiles installation complete!${NC}"
    echo -e "${GREEN}════════════════════════════════════════════════${NC}"
    echo ""
    echo "  Configs backed up to: $BACKUP_DIR"
    echo "  Dotfiles directory:   $DOTFILES_DIR"
    echo ""
    echo "  Next steps:"
    echo "    1. Run: exec zsh"
    echo "       └─ Switches your current session to zsh immediately."
    echo "          Future logins will use zsh automatically (no restart needed)."
    echo "    2. In tmux, press prefix + I to install tmux plugins"
    echo "    3. Open nvim — plugins will auto-install on first launch"
    echo "    4. Edit $PARAMS_FILE for personal defaults"
    echo "    5. Edit ~/.config/zsh/conf.d/99-local.zsh for machine-specific shell tweaks"
    echo ""
}

# ─── Skip helper ─────────────────────────────────────────────────────────────

# Populated from --skip=a,b,c flag
SKIP_STEPS=()

should_skip() {
    local step="$1"
    for s in "${SKIP_STEPS[@]}"; do
        [[ "$s" == "$step" ]] && return 0
    done
    return 1
}

run_step() {
    local name="$1"; shift
    if should_skip "$name"; then
        warn "Skipping: $name"
    else
        "$@"
    fi
}

# ─── Run all steps (full install) ────────────────────────────────────────────

install_all() {
    preflight
    run_step personalize     install_personal_config
    run_step backup          backup
    run_step packages        install_packages
    run_step omz             install_omz
    run_step omz-plugins     install_omz_plugins
    run_step tpm             install_tpm
    run_step nerd-font       install_nerd_font
    run_step stow            install_stow
    run_step local-conf      install_local_conf
    run_step default-shell   install_default_shell
    summary
}

# ─── Help ─────────────────────────────────────────────────────────────────────

show_help() {
    echo "Usage: ./install.sh [command] [--skip=step1,step2,...]"
    echo ""
    echo "Commands:"
    echo "  (no args)       Run full installation"
    echo "  packages        Install brew/apt/dnf packages"
    echo "  personalize     Create local params and Git identity config"
    echo "  omz             Install oh-my-zsh"
    echo "  omz-plugins     Clone oh-my-zsh custom plugins"
    echo "  tpm             Install Tmux Plugin Manager"
    echo "  nerd-font       Install configured Nerd Font (default: Hack)"
    echo "  stow            Create symlinks with GNU Stow"
    echo "  local-conf      Create 99-local.zsh template"
    echo "  default-shell   Set zsh as default shell"
    echo "  backup          Backup existing configs"
    echo "  help            Show this help"
    echo ""
    echo "Options:"
    echo "  --skip=a,b,...  Skip one or more steps during full install"
    echo ""
    echo "Examples:"
    echo "  ./install.sh --skip=default-shell"
    echo "  ./install.sh --skip=personalize,default-shell"
    echo "  ./install.sh --skip=nerd-font,omz-plugins"
}

# ─── Dispatcher ───────────────────────────────────────────────────────────────

# Parse --skip=a,b,c from any position in args
ARGS=()
for arg in "$@"; do
    if [[ "$arg" == --skip=* ]]; then
        IFS=',' read -ra SKIP_STEPS <<< "${arg#--skip=}"
    else
        ARGS+=("$arg")
    fi
done
set -- "${ARGS[@]}"

case "${1:-all}" in
    all)            install_all ;;
    packages)       preflight && install_packages ;;
    personalize)    preflight_git && install_personal_config ;;
    omz)            preflight && install_omz ;;
    omz-plugins)    preflight && install_omz_plugins ;;
    tpm)            preflight && install_tpm ;;
    nerd-font)      preflight && install_nerd_font ;;
    stow)           install_stow ;;
    local-conf)     install_local_conf ;;
    default-shell)  install_default_shell ;;
    backup)         backup ;;
    help|--help|-h) show_help ;;
    *)              err "Unknown command: $1" && show_help && exit 1 ;;
esac
