format = """
$directory\
$git_branch\
$git_status\
$fill\
$cmd_duration\
$line_break\
$character"""

right_format = """$nodejs$python$rust$golang"""

[directory]
truncation_length = 3
truncate_to_repo = false

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"

[cmd_duration]
min_time = 2_000
format = "[$duration]($style) "

[fill]
symbol = " "

[nodejs]
format = "[$symbol($version)]($style) "
detect_files = ["package.json", ".node-version"]

[python]
format = "[$symbol($version)]($style) "

[rust]
format = "[$symbol($version)]($style) "

[golang]
format = "[$symbol($version)]($style) "
